server:
  port: 8084
spring:
  application:
    name: oauth_client_service
  security:
    oauth2:
      client:
        provider:
          test:
            token-uri: http://localhost:64200/oauth2/token
        registration:
          test:
            provider: test
            client-id: localhost
            client-secret: localhost
            authorization-grant-type: client_credentials
            client-name: Spring Boot Auth Server

oauth2:
  registration:
    id: test
resource:
  base: http://localhost:64203
  path: /test
